# Generated by Django 2.2.6 on 2019-11-03 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
